apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-config
  namespace: recommendation
data:
  LOG_LEVEL: "INFO"
  # Database configuration (use secrets for sensitive data)
  DATABASE_HOST: "mysql.database.svc.cluster.local"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "dianshu_backend"

  # Redis configuration
  REDIS_HOST: "redis.recommendation.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  # MLflow configuration
  MLFLOW_TRACKING_URI: "http://mlflow.recommendation.svc.cluster.local:5000"

  # Application settings
  WORKERS: "4"
  MAX_REQUEST_SIZE: "10485760"  # 10MB
  REQUEST_TIMEOUT: "30"
