---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommendation-models-pvc
  namespace: recommendation
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommendation-data-pvc
  namespace: recommendation
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
