name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HF_HUB_OFFLINE: "1"
      HF_HOME: ${{ github.workspace }}/hf_cache
      SENTENCE_TRANSFORMERS_HOME: ${{ github.workspace }}/hf_cache
      TRANSFORMERS_CACHE: ${{ github.workspace }}/hf_cache
      CLIP_MODEL_PATH: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Prepare cache directory
        run: mkdir -p "$HF_HOME"

      - name: Run pytest
        run: |
          pytest

      - name: Train models (dry run)
        env:
          MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns
          MLFLOW_EXPERIMENT_NAME: ci_dataset_recommendation
        run: |
          python -m pipeline.train_models

      - name: Evaluate models
        run: |
          python -m pipeline.evaluate
