name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: |
          pytest

      - name: Train models (dry run)
        env:
          MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns
          MLFLOW_EXPERIMENT_NAME: ci_dataset_recommendation
        run: |
          python -m pipeline.train_models

      - name: Evaluate models
        run: |
          python -m pipeline.evaluate
